name: "Java"

on:
    push:
        branches:
            -main
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: "Build"
        runs-on: "ubuntu-latest"

        steps:
            - name: "CLone repository"
              uses: actions/checkout@3

            - name: "Build project "
              run: ./gradlew build